# Originally inspired by Cloudflare Wrangler
# https://github.com/cloudflare/wrangler2/blob/main/.github/workflows/release.yml

name: Release

on:
  push:
    branches:
      - "*"

jobs:
  release:
    name: Create a PR for release workflow
    runs-on: ubuntu-latest
    steps:
      - name: Instal PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pnpm install

      - name: Build zip
        run: pnpm build --if-present

      - name: Create Version PR
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        #   version: node .github/changeset-version.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
